### ISSUE TITLE
Since plasma 5.4(i guess) applet cannot update weather info.

### ISSUE THREAD

**Issue by FedeDP** [kotelnik/plasma-applet-weather-widget#7] opened 2015-08-21 09:56 UTC
Hi! 
It seems that since i upgraded to plasma 5.4, applet is no more able to update weather informations, both in system tray applet, and in normal plasmoid; see screenshot:
![screenshot_20150821_115158](https://cloud.githubusercontent.com/assets/5837210/9405793/2a89e442-47fb-11e5-920d-09e21ec1c952.png)

As you can see latest info available in system tray applet are the ones remained since the last time it updated; after tomorrow i'll only have "0 0 0 0" columns :D .
Plasmoid was added just for the screenshot and it cannot update neither.
I guess it is plasma 5.4 update because 7 days ago i installed plasma 5.4 beta, and since 7 days the applet cannot update.

**Comment by kotelnik** [comment] 2015-08-22 09:30
Thanks for report, I try to fix that before plasma 5.4 is stable. I already got one similar report: https://github.com/kotelnik/plasma-applet-weather-widget/issues/6

**Comment by kotelnik** [comment] 2015-08-22 09:30
Closing as duplicate of https://github.com/kotelnik/plasma-applet-weather-widget/issues/6

**Closed by kotelnik** 2015-08-22 09:30 UTC
