### ISSUE TITLE
bug: Temperature information for today is missing, first column displays next day temp. 

### ISSUE THREAD

**Issue by JoinJoin** [kotelnik/plasma-applet-weather-widget#30] opened 2016-04-03 10:30 UTC
There is no hourly (more like 6 hour interval) temperature information for today, except on the chart. In other words, the bottom part, where you got the table for the week, first column show tomorrows information, not today's. 

It's not only confusing but also a bit annoying too.

**Comment by kotelnik** [comment] 2016-04-04 17:55
Hi! Thanks for report! This is interesting. I cannot reproduce this issue. I suppose you are using latest version. What provider do you use - yr.no or OWM? And what location? Is there a special corner case (e.g. time of day) when this issue is present or is it there all the time?

**Comment by kotelnik** [comment] 2016-08-08 22:22
Since there was no additional info on this, I'm closing it. Please feel free to reopen when necessary :).

**Closed by kotelnik** 2016-08-08 22:22 UTC
